### ISSUE TITLE
saving screenshot image

### ISSUE THREAD

**Issue by jojo05** [bunsenapp/go-selenium#2]
I get the "image: unknown format" err when trying to save the image. Any ideas how this should be done?

Thanks

dec, err := scs.ImageBytes()
if err != nil || len(dec) == 0 {
    fmt.Println("imagebytes:", err)
    return
}

// convert []byte to image for saving to file
img, format, err := image.Decode(bytes.NewReader(dec))
 fmt.Println("decode:", format, err)

**Comment by jojo05** [comment]
If I save the bytes to a png file it works. 
Would be nice to be able to get an image.Image to add anotations, etc ..

**Comment by jojo05** [comment]
using _ "image/png" allows me to decode the image.

sorry for the noise. You can close the issue

**Comment by heraclmene** [comment]
No problem - I'll resolve this with a commit to advise others on how the `ImageBytes` should be utilised (through the image/png library).

**Comment by medyagh** [comment]
@jojo05 could you please share how you used image/png to decode the image? I tried to do it with image/png I got this error

```

: cannot use byteimg (type *goselenium.ScreenshotResponse) as type image.Image in argument to png.Encode:
	*goselenium.ScreenshotResponse does not implement image.Image (missing At method)

```
