### ISSUE TITLE
multiple concurrent requests

### ISSUE THREAD

**Issue by jojo05** [bunsenapp/go-selenium#3]
What approach do you recommend for multiple concurrent requests?
Should each goroutine in the pool create a driver and a session or just the session ?
Also, how can I get the browser response headers ?

Thanks

**Comment by heraclmene** [comment]
Hi,

Each goroutine in the pool should create its own drivers and sessions. I'd be careful though, the two Max* variables (MaxInstances and MaxSessions) may cause you a few problems. In the Docker images, these are set to 1 for both.

Regarding browser response headers, the Selenium remote driver API is intended *only* to emulate user actions (i.e. if I click a button and a 500 error occurs, all the user would do is check to see an error is on the page). It is not designed for header manipulation/investigation. If you need to do this, I'd suggest the raw net/http library or another application.

**Comment by jojo05** [comment]
Hi, 
I am not very familiar with Docker. Do I need to create a new instance and modify the variables ?
Thanks

**Comment by heraclmene** [comment]
I guess you can do something like `docker run -p 4444:4444 -d -e NODE_MAX_INSTANCES=10 -e NODE_MAX_SESSIONS=10 selenium/firefox-standalone`.

**Comment by jojo05** [comment]
Just for the record, the sessions variable is NODE_MAX_SESSION, without the "S"

https://hub.docker.com/r/selenium/node-firefox/~/dockerfile/

**Comment by heraclmene** [comment]
Apologies - thank you for the correction.
