### ISSUE TITLE
error reporting

### ISSUE THREAD

**Issue by jojo05** [bunsenapp/go-selenium#4]
It seems that there is some duplicity between error codes and .State != "success". Do both need to be checked ?

Also, when I get a tab crash, I am not able to capture the error. I get the error when I look at the html or the screenshot. Any ideas how to capture the tab crash or even avoid it if possible?

thanks

**Comment by heraclmene** [comment]
Would you be able to provide some examples where this does not work please?

**Comment by jojo05** [comment]
Below is the test code ,  try with url http://elpais.com 
This fails with Firefox but works ok with Chrome. In general, when I try a set of pages I get 10% tab crashes and I am not able to capture any error.

I am running Fedora 23 x86_64 and my browser is ff48 (selenium has ff50). I run selenium via docker. The test page above works ok on my browser but not in selenium

thanks

[test.txt](https://github.com/bunsenapp/go-selenium/files/705868/test.txt)

**Comment by heraclmene** [comment]
Regarding your point of errors and the 'State' property: if there is any error returned, any at all, then you should discount the response value as per Go best practices. The error should give you everything you need to know.

I've just ran your script 5 times and have not experienced any issues; are you sure it's not something to do with your local machine?

**Comment by jojo05** [comment]
Ok, the page works now. I imagine the page had some plugin yesterday that it cause it to crash but not with today's content. I'll check a few popular pages and send you a new URL.

Wrt errors, I understand your comment as saying that if checking for Go errors, then .State can be ignored. That's what I thought but wanted to confirm

Thanks

**Comment by heraclmene** [comment]
Welcome.

**Comment by jojo05** [comment]
3 examples from the top100 domains (in opendns list):

http://www.addthis.com/
http://www.mathtag.com/
http://www.msn.com/

Note that this pages don't return any error (bad a page with bad DNS would return the error). Tab crash snapshot included

I did some simple tests with Java or Flash pages and they don't cause this crash, so the issue mast be different. 
      
![addthis com](https://cloud.githubusercontent.com/assets/1174668/21956735/49a8b8e2-da87-11e6-9489-afc860fa435f.jpg)

**Comment by jojo05** [comment]
"bad a page" -> I meant "BUT a page"

**Comment by heraclmene** [comment]
I can't get these tabs to crash so am unable to replicate the issue; do you have an exact set of steps?

**Comment by jojo05** [comment]
The culprit was Flash plugin not installed on my system. While some flash pages did not crash (like the Adobe one), others did.
It looks like the Docker image calls is own Firefox, but this uses the plugins in the system. Does this make sense?

**Comment by heraclmene** [comment]
It does, sort of, apart from the fact I can not see anywhere in the Dockerfiles where this happens.

**Comment by jojo05** [comment]
I resolved all the issues, 
but my final question is: Did you repro the issues with a docker image or a normal setup ?

**Comment by heraclmene** [comment]
I was unable to reproduce it in either environment.
