### ISSUE TITLE
i think the wait function is not work corrently

### ISSUE THREAD

**Issue by zhangweilun** [bunsenapp/go-selenium#5]
_, err = element.Click()
	if err != nil {
		panic(err)
	}
	ok := driver.Wait(goselenium.UntilElementPresent(goselenium.ByXPath(`//*[@id="J_tabMenu"]/ul/li[23]/div[1]/h2`)),
		3*time.Second, 2*time.Second)
	if !ok {
		fmt.Println("Wait timed out :<")
		return
	}
	html, err := driver.PageSource()
	fmt.Println(html)
	if err != nil {
		fmt.Println(err)
	}
 there is the source code,but it s not work,because the wait function , i do not kow the reason

**Comment by elsyms** [comment]
Does it fail? What errors do you get?
