### ISSUE TITLE
how to set the proxy

### ISSUE THREAD

**Issue by zhangweilun** [bunsenapp/go-selenium#6]
i want to set the proxy with this library

**Comment by zhangweilun** [comment]
please help

**Comment by vedhavyas** [comment]
@elsyms I can take this up as I have a requirement for this. Do you take PRs?

**Comment by elsyms** [comment]
@vedhavyas Of course. If you cannot do it I'll happily pick it up.

**Comment by vedhavyas** [comment]
@elsyms go ahead 👍
